line-length = 88
target-version = "py312"

[lint]
select = ["E", "F", "B", "I", "N", "UP", "PL", "RUF"]
ignore = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"